### PR TITLE
Add Clang to linux-appimage, linux-frozen and linux-mingw

### PR DESCRIPTION
**Pull request by Rokkubro**
Add clang to the linux images(bar frozen) so it can be used when building

### CODE REVIEW

**Comment by FearlessTobi** [comment]
Please squash your commits into one.

**Review by FearlessTobi — CHANGES_REQUESTED** [review]
Blocking for the reasons mentioned in https://github.com/citra-emu/citra/pull/6609#pullrequestreview-1480047163.

**Comment by Steveice10** [comment]
Can probably be closed since we are now doing LTO with GCC fine, and don't intend to switch compilers.

**Comment by FearlessTobi** [comment]
Agreed, I don't have permission to close this though.

**Pull request closed without merging**
